### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by HyperSkys** [andrei923/LeafBedWars#1]
How do you change name?

**Comment by andrei923** [comment]
which ones? the stats one? the "play" ones? or all of them?

**Comment by HyperSkys** [comment]
The SHOP Npc's

**Comment by HyperSkys** [comment]
For buying items and stuff

**Comment by HyperSkys** [comment]
ex. Obsidian

**Comment by andrei923** [comment]
try this configuration for shop https://github.com/andrei923/LeafBedWars/blob/master/shop.yml

**Comment by HyperSkys** [comment]
I did it is still not working sometimes they will spawn but I try and click on them and it doesn't work and if I rejoin most of the time they disappear
